/// Typed data models for ClairvoyanceEngine 2.0 insights.
library;

/// Severity levels for financial insights.
enum InsightSeverity {
  info, // Neutral observation
  positive, // Good financial behavior
  warning, // Needs attention
  critical, // Immediate action required
}

/// Categories of financial insights.
enum InsightCategory {
  spending, // Spending anomalies
  budget, // Budget & burn rate
  savings, // Savings intelligence
  income, // Income & cash flow
  lifestyle, // Lifestyle & behavioral
  trend, // Trend analysis
  prediction, // Forward-looking predictions
  reinforcement, // Positive reinforcement
}

/// A single financial insight generated by the ClairvoyanceEngine.
class Insight {
  final String emoji;
  final String title;
  final String description;
  final InsightSeverity severity;
  final InsightCategory category;
  final String? actionTip;

  const Insight({
    required this.emoji,
    required this.title,
    required this.description,
    required this.severity,
    required this.category,
    this.actionTip,
  });

  /// Legacy compatibility: converts to the old String format.
  @override
  String toString() => '$emoji $title: $description';
}
